language: python
python: "2.7"
install:
    - wget https://launchpad.net/plone/4.3/4.3.2/+download/Plone-4.3.2-UnifiedInstaller.tgz
    - tar -xf Plone-4.3.2-UnifiedInstaller.tgz
    - tar -xf Plone-4.3.2-UnifiedInstaller/packages/buildout-cache.tar.bz2

    - virtualenv --no-setuptools .
    - bin/python bootstrap.py
    - bin/buildout -c travis.cfg install test
script: bin/test