language: python
python: "2.7"
install:
    - wget https://launchpad.net/plone/4.3/4.3.3/+download/Plone-4.3.3-UnifiedInstaller.tgz
    - tar -xf Plone-4.3.3-UnifiedInstaller.tgz
    - tar -xf Plone-4.3.3-UnifiedInstaller/packages/buildout-cache.tar.bz2

    - virtualenv --no-setuptools .
    - bin/python bootstrap.py --setuptools-version 7.0 --version 2.2.5
    - bin/buildout -c travis.cfg install test
script: bin/test